#!/usr/bin/env bash
name="qt6-quicktimeline"
version="6.7.0"
description="Qt module for keyframe-based timeline construction"
source="https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtquicktimeline-everywhere-src-${version}.tar.xz"
depends="qt6-base,qt6-declarative"
builddepend="cmake"
group="dev.qt"


setup () {
	cd $SOURCEDIR
	
	cmake -B $BUILDDIR -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_MESSAGE_LOG_LEVEL=STATUS
		


}

build () {
    cmake --build $BUILDDIR
}

package () {
    DESTDIR=$DESTDIR cmake --install $BUILDDIR
}


