#!/usr/bin/env bash
name="qt6-shadertools"
version="6.7.0"
description="Provides functionality for the shader pipeline that allows Qt Quick to operate on Vulkan, Metal, and Direct3D, in addition to OpenGL"
source="https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtshadertools-everywhere-src-${version}.tar.xz"
depends="qt6-base"
builddepend="cmake,perl"
group="dev.qt"


setup () {
	cd $SOURCEDIR
	
	cmake -B $BUILDDIR -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo
		


}

build () {
    cmake --build $BUILDDIR
}

package () {
    DESTDIR=$DESTDIR cmake --install $BUILDDIR
}


