#!/usr/bin/env bash
name="qt5-quickcontrols"
version="5.15.14"
description="Reusable Qt Quick based UI controls to create classic desktop-style user interfaces"
source="https://download.qt.io/official_releases/qt/${version%.*}/${version}/submodules/qtquickcontrols-everywhere-opensource-src-${version}.tar.xz"
depends="qt5-declarative"
builddepend=""
group="dev.qt"

setup() {
export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}


