#!/usr/bin/env bash
name="qt6-tools"
version="6.7.0"
description="A cross-platform application and UI framework"
source="https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qttools-everywhere-src-${version}.tar.xz"
depends="qt6-base"
builddepend="cmake,vulkan-headers"
group="dev.qt"


setup () {
	cd $SOURCEDIR
	
	cmake -B $BUILDDIR -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_MESSAGE_LOG_LEVEL=STATUS
		


}

build () {
    cmake --build $BUILDDIR
}

package () {
    DESTDIR=$DESTDIR cmake --install $BUILDDIR
}


