#!/usr/bin/env bash
name="qt5-imageformats"
version="5.15.14"
description="Plugins for additional image formats: TIFF, MNG, TGA, WBMP"
source="https://download.qt.io/official_releases/qt/${version%.*}/${version}/submodules/qtimageformats-everywhere-opensource-src-${version}.tar.xz"
depends="qt5-base,jasper,libmng,libwebp"
builddepend=""
group="dev.qt"

setup() {
export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

