#!/usr/bin/env bash
name="qt5-quickcontrols2"
version="5.15.14"
description="Next generation user interface controls based on Qt Quick"
source="https://download.qt.io/official_releases/qt/${version%.*}/${version}/submodules/qtquickcontrols2-everywhere-opensource-src-${version}.tar.xz"
depends="qt5-declarative"
builddepend=""
group="dev.qt"

setup() {
export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
