#!/usr/bin/env bash
name="qt5-graphicaleffects"
version="5.15.14"
description="Graphical effects for use with Qt Quick 2"
source="https://download.qt.io/official_releases/qt/${version%.*}/${version}/submodules/qtgraphicaleffects-everywhere-opensource-src-${version}.tar.xz"
depends="qt5-base,qt5-declarative"
builddepend=""
group="dev.qt"

setup() {
export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

