#!/usr/bin/env bash
name="qt5-multimedia"
version="5.15.14"
description="Qt5 - Multimedia support"
source="https://download.qt.io/official_releases/qt/${version%.*}/${version}/submodules/qtmultimedia-everywhere-opensource-src-${version}.tar.xz"
depends="qt5-base,gst-plugins-base,libpulse,openal"
builddepend="qt5-declarative,gst-plugins-bad"
group="dev.qt"

setup() {
export PATH=/usr/bin/qt5:$PATH
	cd $SOURCEDIR
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
